file(READ "${INPUT}" binary HEX)
string(REGEX MATCHALL "........" words "${binary}")
set(output "#pragma once\n#include <cstdint>\nstatic const uint32_t pathtrace_spv[] = {\n")
foreach(word IN LISTS words)
    string(SUBSTRING "${word}" 0 2 a)
    string(SUBSTRING "${word}" 2 2 b)
    string(SUBSTRING "${word}" 4 2 c)
    string(SUBSTRING "${word}" 6 2 d)
    string(APPEND output "0x${d}${c}${b}${a},")
endforeach()
string(APPEND output "\n};\n")
file(WRITE "${OUTPUT}" "${output}")
